# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596186ac24675718ea671aa39fca9ab2035b85cd259a23fcff9905961cb146654e8da55b659b781b56ab105530af800770fffbdbca1ee7321d5e8c79001a0839

test:
  secret_key_base: 0ea3fdc0ccdb365dfdc9700780b490ac2c8518e4688961cc636022d220b42215707c08e02e9430bf96d8824a600eb7deaec092c9a404b86efe9e7d410abbe50f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
